language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rumlauf/docker-react -f Dockerfile.dev .

# Commands that need to be executed to run the tests
script:    
    - docker run -e CI=true rumlauf/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-487437176526"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_access_key
    secret_key_id: $AWS_secret_key