language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t rumlauf/docker-react -f Dockerfile.dev .

# Commands that need to be executed to run the tests
script:    
    - docker run -e CI=true rumlauf/docker-react npm run test
